import { themeVars } from './theme';

export const globalPalette = {
	lightForegroundText: `var(${themeVars.lightForegroundText})`,
	lightForegroundAction: `var(${themeVars.lightForegroundAction})`,
	lightForegroundFocus: `var(${themeVars.lightForegroundFocus})`,
	lightForegroundMuted: `var(${themeVars.lightForegroundMuted})`,
	lightBackgroundBody: `var(${themeVars.lightBackgroundBody})`,
	lightBackgroundShade: `var(${themeVars.lightBackgroundShade})`,
	lightBackgroundBodyAlt: `var(${themeVars.lightBackgroundBodyAlt})`,
	lightBackgroundShadeAlt: `var(${themeVars.lightBackgroundShadeAlt})`,
	lightSelected: `var(${themeVars.lightSelected})`,
	lightSelectedMuted: `var(${themeVars.lightSelectedMuted})`,
	lightBorder: `var(${themeVars.lightBorder})`,
	lightAccent: `var(${themeVars.lightAccent}`,
	lightOverlay: `var(${themeVars.lightOverlay}`,
	lightSystemSuccess: `var(${themeVars.lightSystemSuccess})`,
	lightSystemSuccessMuted: `var(${themeVars.lightSystemSuccessMuted})`,
	lightSystemError: `var(${themeVars.lightSystemError})`,
	lightSystemErrorMuted: `var(${themeVars.lightSystemErrorMuted})`,
	lightSystemWarning: `var(${themeVars.lightSystemWarning})`,
	lightSystemWarningMuted: `var(${themeVars.lightSystemWarningMuted})`,
	lightSystemInfo: `var(${themeVars.lightSystemInfo})`,
	lightSystemInfoMuted: `var(${themeVars.lightSystemInfoMuted})`,
	darkForegroundText: `var(${themeVars.darkForegroundText})`,
	darkForegroundAction: `var(${themeVars.darkForegroundAction})`,
	darkForegroundFocus: `var(${themeVars.darkForegroundFocus})`,
	darkForegroundMuted: `var(${themeVars.darkForegroundMuted})`,
	darkBackgroundBody: `var(${themeVars.darkBackgroundBody})`,
	darkBackgroundShade: `var(${themeVars.darkBackgroundShade})`,
	darkBackgroundBodyAlt: `var(${themeVars.darkBackgroundBodyAlt})`,
	darkBackgroundShadeAlt: `var(${themeVars.darkBackgroundShadeAlt})`,
	darkSelected: `var(${themeVars.darkSelected})`,
	darkSelectedMuted: `var(${themeVars.darkSelectedMuted})`,
	darkBorder: `var(${themeVars.darkBorder})`,
	darkAccent: `var(${themeVars.darkAccent}`,
	darkOverlay: `var(${themeVars.darkOverlay}`,
	darkSystemSuccess: `var(${themeVars.darkSystemSuccess})`,
	darkSystemSuccessMuted: `var(${themeVars.darkSystemSuccessMuted})`,
	darkSystemError: `var(${themeVars.darkSystemError})`,
	darkSystemErrorMuted: `var(${themeVars.darkSystemErrorMuted})`,
	darkSystemWarning: `var(${themeVars.darkSystemWarning})`,
	darkSystemWarningMuted: `var(${themeVars.darkSystemWarningMuted})`,
	darkSystemInfo: `var(${themeVars.darkSystemInfo})`,
	darkSystemInfoMuted: `var(${themeVars.darkSystemInfoMuted})`,
} as const;
