import { Theme } from './theme';

export const printTheme: Theme = {
	lightForegroundText: 'black',
	lightForegroundAction: 'black',
	lightForegroundSelected: 'black',
	lightForegroundFocus: 'black',
	lightForegroundMuted: 'black',
	lightBackgroundBody: 'white',
	lightBackgroundShade: 'white',
	lightBackgroundBodyAlt: 'white',
	lightBackgroundShadeAlt: 'white',
	lightBorder: 'black',
	lightBorderMuted: 'black',
	lightAccent: 'black',
	lightOverlay: 'white',
	lightSystemError: 'black',
	lightSystemSuccess: 'black',
	lightSystemWarning: 'black',
	lightSystemInfo: 'black',
	lightSystemErrorMuted: 'white',
	lightSystemSuccessMuted: 'white',
	lightSystemWarningMuted: 'white',
	lightSystemInfoMuted: 'white',
	darkForegroundText: 'black',
	darkForegroundAction: 'black',
	darkForegroundSelected: 'black',
	darkForegroundFocus: 'black',
	darkForegroundMuted: 'black',
	darkBackgroundBody: 'white',
	darkBackgroundShade: 'white',
	darkBackgroundBodyAlt: 'white',
	darkBackgroundShadeAlt: 'white',
	darkBorder: 'black',
	darkBorderMuted: 'black',
	darkAccent: 'black',
	darkOverlay: 'white',
	darkSystemError: 'black',
	darkSystemErrorMuted: 'white',
	darkSystemSuccess: 'black',
	darkSystemSuccessMuted: 'white',
	darkSystemWarningMuted: 'white',
	darkSystemWarning: 'black',
	darkSystemInfo: 'black',
	darkSystemInfoMuted: 'white',
} as const;
