import { css } from '@emotion/react';
import { themeVars } from './theme';

// Box Palette

const boxPaletteVars = {
	foregroundText: '--agds-foreground-text',
	foregroundAction: '--agds-foreground-action',
	foregroundFocus: '--agds-foreground-focus',
	foregroundMuted: '--agds-foreground-muted',
	backgroundBody: '--agds-background-body',
	backgroundShade: '--agds-background-shade',
	backgroundBodyAlt: '--agds-background-body-alt',
	backgroundShadeAlt: '--agds-background-shade-alt',
	border: '--agds-border',
	borderMuted: '--agds-border-muted',
	accent: '--agds-accent',
	systemSuccess: '--agds-system-success',
	systemSuccessMuted: '--agds-system-success-muted',
	systemWarning: '--agds-system-warning',
	systemWarningMuted: '--agds-system-warning-muted',
	systemInfo: '--agds-system-info',
	systemInfoMuted: '--agds-system-info-muted',
	systemError: '--agds-system-error',
	systemErrorMuted: '--agds-system-error-muted',
};

export const boxPalettes = {
	light: css({
		[boxPaletteVars.foregroundText]: `var(${themeVars.lightForegroundText})`,
		[boxPaletteVars.foregroundAction]: `var(${themeVars.lightForegroundAction})`,
		[boxPaletteVars.foregroundFocus]: `var(${themeVars.lightForegroundFocus})`,
		[boxPaletteVars.foregroundMuted]: `var(${themeVars.lightForegroundMuted})`,
		[boxPaletteVars.backgroundBody]: `var(${themeVars.lightBackgroundBody})`,
		[boxPaletteVars.backgroundShade]: `var(${themeVars.lightBackgroundShade})`,
		[boxPaletteVars.backgroundBodyAlt]: `var(${themeVars.lightBackgroundBodyAlt})`,
		[boxPaletteVars.backgroundShadeAlt]: `var(${themeVars.lightBackgroundShadeAlt})`,
		[boxPaletteVars.border]: `var(${themeVars.lightBorder})`,
		[boxPaletteVars.borderMuted]: `var(${themeVars.lightBorderMuted})`,
		[boxPaletteVars.accent]: `var(${themeVars.lightAccent})`,
		[boxPaletteVars.systemError]: `var(${themeVars.lightSystemError})`,
		[boxPaletteVars.systemSuccess]: `var(${themeVars.lightSystemSuccess})`,
		[boxPaletteVars.systemWarning]: `var(${themeVars.lightSystemWarning})`,
		[boxPaletteVars.systemInfo]: `var(${themeVars.lightSystemInfo})`,
		[boxPaletteVars.systemSuccessMuted]: `var(${themeVars.lightSystemSuccessMuted})`,
		[boxPaletteVars.systemInfoMuted]: `var(${themeVars.lightSystemInfoMuted})`,
		[boxPaletteVars.systemWarningMuted]: `var(${themeVars.lightSystemWarningMuted})`,
		[boxPaletteVars.systemErrorMuted]: `var(${themeVars.lightSystemErrorMuted})`,
	}),
	dark: css({
		[boxPaletteVars.foregroundText]: `var(${themeVars.darkForegroundText})`,
		[boxPaletteVars.foregroundAction]: `var(${themeVars.darkForegroundAction})`,
		[boxPaletteVars.foregroundFocus]: `var(${themeVars.darkForegroundFocus})`,
		[boxPaletteVars.foregroundMuted]: `var(${themeVars.darkForegroundMuted})`,
		[boxPaletteVars.backgroundBody]: `var(${themeVars.darkBackgroundBody})`,
		[boxPaletteVars.backgroundShade]: `var(${themeVars.darkBackgroundShade})`,
		[boxPaletteVars.backgroundBodyAlt]: `var(${themeVars.darkBackgroundBodyAlt})`,
		[boxPaletteVars.backgroundShadeAlt]: `var(${themeVars.darkBackgroundShadeAlt})`,
		[boxPaletteVars.border]: `var(${themeVars.darkBorder})`,
		[boxPaletteVars.borderMuted]: `var(${themeVars.darkBorderMuted})`,
		[boxPaletteVars.accent]: `var(${themeVars.darkAccent})`,
		[boxPaletteVars.systemSuccess]: `var(${themeVars.darkSystemSuccess})`,
		[boxPaletteVars.systemSuccessMuted]: `var(${themeVars.darkSystemSuccessMuted})`,
		[boxPaletteVars.systemError]: `var(${themeVars.darkSystemError})`,
		[boxPaletteVars.systemErrorMuted]: `var(${themeVars.darkSystemErrorMuted})`,
		[boxPaletteVars.systemWarning]: `var(${themeVars.darkSystemWarning})`,
		[boxPaletteVars.systemWarningMuted]: `var(${themeVars.darkSystemWarningMuted})`,
		[boxPaletteVars.systemInfo]: `var(${themeVars.darkSystemInfo})`,
		[boxPaletteVars.systemInfoMuted]: `var(${themeVars.darkSystemInfoMuted})`,
	}),
} as const;

export type BoxPalette = keyof typeof boxPalettes;

export const boxPalette = {
	foregroundText: `var(${boxPaletteVars.foregroundText})`,
	foregroundAction: `var(${boxPaletteVars.foregroundAction})`,
	foregroundFocus: `var(${boxPaletteVars.foregroundFocus})`,
	foregroundMuted: `var(${boxPaletteVars.foregroundMuted})`,
	backgroundBody: `var(${boxPaletteVars.backgroundBody})`,
	backgroundShade: `var(${boxPaletteVars.backgroundShade})`,
	backgroundBodyAlt: `var(${boxPaletteVars.backgroundBodyAlt})`,
	backgroundShadeAlt: `var(${boxPaletteVars.backgroundShadeAlt})`,
	border: `var(${boxPaletteVars.border})`,
	borderMuted: `var(${boxPaletteVars.borderMuted})`,
	accent: `var(${boxPaletteVars.accent})`,
	systemError: `var(${boxPaletteVars.systemError})`,
	systemErrorMuted: `var(${boxPaletteVars.systemErrorMuted})`,
	systemSuccess: `var(${boxPaletteVars.systemSuccess})`,
	systemSuccessMuted: `var(${boxPaletteVars.systemSuccessMuted})`,
	systemWarning: `var(${boxPaletteVars.systemWarning})`,
	systemWarningMuted: `var(${boxPaletteVars.systemWarningMuted})`,
	systemInfo: `var(${boxPaletteVars.systemInfo})`,
	systemInfoMuted: `var(${boxPaletteVars.systemInfoMuted})`,
};
