import { themeVars } from './theme';

export const globalPalette = {
	lightForegroundText: `var(${themeVars.lightForegroundText})`,
	lightForegroundAction: `var(${themeVars.lightForegroundAction})`,
	lightForegroundFocus: `var(${themeVars.lightForegroundFocus})`,
	lightForegroundMuted: `var(${themeVars.lightForegroundMuted})`,
	lightBackgroundBody: `var(${themeVars.lightBackgroundBody})`,
	lightBackgroundShade: `var(${themeVars.lightBackgroundShade})`,
	lightBackgroundBodyAlt: `var(${themeVars.lightBackgroundBodyAlt})`,
	lightBackgroundShadeAlt: `var(${themeVars.lightBackgroundShadeAlt})`,
	lightBackgroundSuccess: `var(${themeVars.lightBackgroundSuccess})`,
	lightBackgroundError: `var(${themeVars.lightBackgroundError})`,
	lightBackgroundInfo: `var(${themeVars.lightBackgroundInfo})`,
	lightBackgroundWarning: `var(${themeVars.lightBackgroundWarning})`,
	lightBorder: `var(${themeVars.lightBorder})`,
	lightAccent: `var(${themeVars.lightAccent}`,
	lightError: `var(${themeVars.lightError})`,
	lightSuccess: `var(${themeVars.lightSuccess})`,
	lightWarning: `var(${themeVars.lightWarning})`,
	lightInfo: `var(${themeVars.lightInfo})`,
	darkForegroundText: `var(${themeVars.darkForegroundText})`,
	darkForegroundAction: `var(${themeVars.darkForegroundAction})`,
	darkForegroundFocus: `var(${themeVars.darkForegroundFocus})`,
	darkForegroundMuted: `var(${themeVars.darkForegroundMuted})`,
	darkBackgroundBody: `var(${themeVars.darkBackgroundBody})`,
	darkBackgroundShade: `var(${themeVars.darkBackgroundShade})`,
	darkBackgroundBodyAlt: `var(${themeVars.darkBackgroundBodyAlt})`,
	darkBackgroundShadeAlt: `var(${themeVars.darkBackgroundShadeAlt})`,
	darkBackgroundSuccess: `var(${themeVars.darkBackgroundSuccess})`,
	darkBackgroundError: `var(${themeVars.darkBackgroundError})`,
	darkBackgroundInfo: `var(${themeVars.darkBackgroundInfo})`,
	darkBackgroundWarning: `var(${themeVars.darkBackgroundWarning})`,
	darkBorder: `var(${themeVars.darkBorder})`,
	darkAccent: `var(${themeVars.darkAccent}`,
	darkError: `var(${themeVars.darkError})`,
	darkSuccess: `var(${themeVars.darkSuccess})`,
	darkWarning: `var(${themeVars.darkWarning})`,
	darkInfo: `var(${themeVars.darkInfo})`,
} as const;
