// Default theme from GOLD.
export const goldTheme = {
	lightForegroundText: '#313131',
	lightForegroundAction: '#00698f',
	lightForegroundFocus: '#9263de',
	lightForegroundMuted: '#626262',
	lightBackgroundBody: '#FFFFFF',
	lightBackgroundShade: '#f5f5f5',
	lightBackgroundBodyAlt: '#ebebeb',
	lightBackgroundShadeAlt: '#e0e0e0',
	lightBackgroundError: '#fdf2f2',
	lightBackgroundSuccess: '#f3faf8',
	lightBackgroundWarning: '#fffaf2',
	lightBackgroundInfo: '#f2fcfe',
	lightBorder: '#808080',
	lightBorderMuted: '#D3D3D3',
	lightBorderInput: '#808080',
	darkForegroundText: '#FFFFFF',
	darkForegroundAction: '#61daff',
	darkForegroundFocus: '#c390f9',
	darkForegroundMuted: '#bdd2d7',
	darkBackgroundBody: '#135e70',
	darkBackgroundShade: '#104f5f',
	darkBackgroundBodyAlt: '#0d414d',
	darkBackgroundShadeAlt: '#0a323c',
	darkBackgroundError: '#fdf2f2',
	darkBackgroundSuccess: '#f3faf8',
	darkBackgroundWarning: '#fffaf2',
	darkBackgroundInfo: '#f2fcfe',
	darkBorder: '#95b7bf',
	darkBorderMuted: '#4D7680',
	darkBorderInput: '#FFFFFF',
	// system colors
	accent: undefined, // accent does not exist in GOLD.
	error: '#d60000',
	success: '#0b996c',
	warning: '#f69900',
	info: '#00bfe9',
} as const;
