export const printTheme = {
	lightForegroundText: 'black',
	lightForegroundAction: 'black',
	lightForegroundFocus: 'black',
	lightForegroundMuted: 'black',
	lightBackgroundBody: 'white',
	lightBackgroundShade: 'white',
	lightBackgroundBodyAlt: 'white',
	lightBackgroundShadeAlt: 'white',
	lightBorder: 'black',
	lightBorderMuted: 'black',
	lightBorderInput: 'black',
	darkForegroundText: 'black',
	darkForegroundAction: 'black',
	darkForegroundFocus: 'black',
	darkForegroundMuted: 'black',
	darkBackgroundBody: 'white',
	darkBackgroundShade: 'white',
	darkBackgroundBodyAlt: 'white',
	darkBackgroundShadeAlt: 'white',
	darkBorder: 'black',
	darkBorderMuted: 'black',
	darkBorderInput: 'black',
	// system colors
	accent: 'black',
	error: 'black',
	errorMuted: 'black',
	success: 'black',
	successMuted: 'black',
	warning: 'black',
	warningMuted: 'black',
	info: 'black',
	infoMuted: 'black',
} as const;
